# helpful link:
#https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages


matrix:
  include:

    - language: cpp
      compiler: gcc
      # Optional: "dist" specifies the operating system ("bionic"=ubuntu18.04)
      dist: bionic
      #install:
      #  - sudo apt-get install -qq cppcheck
      script:
        - cd tests
        - g++ -std=c++11 -I../include -o test_jacobi test.cpp
        #- cppcheck --quiet --error-exitcode=1
        - ./test_jacobi 2 1000 3.0
        - ./test_jacobi 3 1000 3.0
        - ./test_jacobi 4 1000 3.0
        - ./test_jacobi 5 1000 3.0
        - ./test_jacobi 10 100 3.0
        - ./test_jacobi 50 20 3.0
        - cd ../

    - language: cpp
      compiler: clang
      # Optional: "dist" specifies the operating system ("bionic"=ubuntu18.04)
      dist: bionic
      #install:
      #  - sudo apt-get install -qq cppcheck
      script:
        - cd tests
        - clang++ -std=c++11 -I../include -o test_jacobi test.cpp
        #- cppcheck --quiet --error-exitcode=1
        - ./test_jacobi 2 1000 3.0
        - ./test_jacobi 3 1000 3.0
        - ./test_jacobi 4 1000 3.0
        - ./test_jacobi 5 1000 3.0
        - ./test_jacobi 10 100 3.0
        - ./test_jacobi 50 20 3.0
        - cd ../

